swagger: "2.0"
info:
  title: Banking System API
  version: "1.0"
paths:
  /transactions:
    post:
      summary: Add a new transaction
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              amount:
                type: number
              type:
                type: string
                enum: [credit, debit]
              description:
                type: string
      responses:
        201:
          description: Transaction created
    get:
      summary: Retrieve all transactions
      responses:
        200:
          description: List of transactions
  /transactions/{transactionID}:
    get:
      summary: Retrieve a specific transaction
      parameters:
        - name: transactionID
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Transaction details
        404:
          description: Transaction not found
    put:
      summary: Modify a transaction
      parameters:
        - name: transactionID
          in: path
          required: true
          type: integer
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              amount:
                type: number
              type:
                type: string
                enum: [credit, debit]
              description:
                type: string
      responses:
        200:
          description: Transaction updated
        404:
          description: Transaction not found
    delete:
      summary: Remove a transaction
      parameters:
        - name: transactionID
          in: path
          required: true
          type: integer
      responses:
        204:
          description: Transaction deleted
        404:
          description: Transaction not found